<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CategoriesSeeder extends Seeder {

  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $categories = [
      [
        'id'            =>  1,
        'type'          =>  0,
        'name'          =>  'Web Development',
        'desc'          =>  'Web Development',
        'order'         =>  0,
        'parent_id'     =>  null,
      ],
      [
        'id'            =>  2,
        'type'          =>  0,
        'name'          =>  'Web Design',
        'desc'          =>  'Web Design',
        'order'         =>  1,
        'parent_id'     =>  1,
      ],
      [
        'id'            =>  3,
        'type'          =>  0,
        'name'          =>  'Web Programming',
        'desc'          =>  'Web Programming',
        'order'         =>  2,
        'parent_id'     =>  1,
      ],
      [
        'id'            =>  4,
        'type'          =>  0,
        'name'          =>  'Ecommerce',
        'desc'          =>  'Ecommerce',
        'order'         =>  3,
        'parent_id'     =>  1,
      ],
      [
        'id'            =>  5,
        'type'          =>  0,
        'name'          =>  'UI Design',
        'desc'          =>  'UI Design',
        'order'         =>  4,
        'parent_id'     =>  1,
      ],
      [
        'id'            =>  6,
        'type'          =>  0,
        'name'          =>  'Website QA',
        'desc'          =>  'Website QA',
        'order'         =>  5,
        'parent_id'     =>  1,
      ],
      [
        'id'            =>  7,
        'type'          =>  0,
        'name'          =>  'Website Project Management',
        'desc'          =>  'Website Project Management',
        'order'         =>  6,
        'parent_id'     =>  1,
      ],
      [
        'id'            =>  8,
        'type'          =>  0,
        'name'          =>  'Other - Web Development',
        'desc'          =>  'Other - Web Development',
        'order'         =>  7,
        'parent_id'     =>  1,
      ],
      [
        'id'            =>  9,
        'type'          =>  0,
        'name'          =>  'Software Development',
        'desc'          =>  'Software Development',
        'order'         =>  1,
        'parent_id'     =>  null,
      ],
      [
        'id'            =>  10,
        'type'          =>  0,
        'name'          =>  'Desktop Applications',
        'desc'          =>  'Desktop Applications',
        'order'         =>  0,
        'parent_id'     =>  9,
      ],
      [
        'id'            =>  11,
        'type'          =>  0,
        'name'          =>  'Game Development',
        'desc'          =>  'Game Development',
        'order'         =>  1,
        'parent_id'     =>  9,
      ],
      [
        'id'            =>  12,
        'type'          =>  0,
        'name'          =>  'Scripts & Utilities',
        'desc'          =>  'Scripts & Utilities',
        'order'         =>  2,
        'parent_id'     =>  9,
      ],
      [
        'id'            =>  13,
        'type'          =>  0,
        'name'          =>  'Software Plug-ins',
        'desc'          =>  'Software Plug-ins',
        'order'         =>  3,
        'parent_id'     =>  9,
      ],
      [
        'id'            =>  14,
        'type'          =>  0,
        'name'          =>  'Mobile Apps',
        'desc'          =>  'Mobile Apps',
        'order'         =>  4,
        'parent_id'     =>  9,
      ],
      [
        'id'            =>  15,
        'type'          =>  0,
        'name'          =>  'Application Interface Design',
        'desc'          =>  'Application Interface Design',
        'order'         =>  5,
        'parent_id'     =>  9,
      ],
      [
        'id'            =>  16,
        'type'          =>  0,
        'name'          =>  'Software Project Management',
        'desc'          =>  'Software Project Management',
        'order'         =>  6,
        'parent_id'     =>  9,
      ],
      [
        'id'            =>  17,
        'type'          =>  0,
        'name'          =>  'Software QA',
        'desc'          =>  'Software QA',
        'order'         =>  7,
        'parent_id'     =>  9,
      ],
      [
        'id'            =>  18,
        'type'          =>  0,
        'name'          =>  'VOIP',
        'desc'          =>  'VOIP',
        'order'         =>  8,
        'parent_id'     =>  9,
      ],
      [
        'id'            =>  19,
        'type'          =>  0,
        'name'          =>  'Other - Software Development',
        'desc'          =>  'Other - Software Development',
        'order'         =>  9,
        'parent_id'     =>  9,
      ],
      [
        'id'            =>  20,
        'type'          =>  0,
        'name'          =>  'Networking & Information Systems',
        'desc'          =>  'Networking & Information Systems',
        'order'         =>  2,
        'parent_id'     =>  null,
      ],
      [
        'id'            =>  21,
        'type'          =>  0,
        'name'          =>  'Network Administration',
        'desc'          =>  'Network Administration',
        'order'         =>  0,
        'parent_id'     =>  20,
      ],
      [
        'id'            =>  22,
        'type'          =>  0,
        'name'          =>  'DBA - Database Administration',
        'desc'          =>  'DBA - Database Administration',
        'order'         =>  1,
        'parent_id'     =>  20,
      ],
      [
        'id'            =>  23,
        'type'          =>  0,
        'name'          =>  'Server Administration',
        'desc'          =>  'Server Administration',
        'order'         =>  2,
        'parent_id'     =>  20,
      ],
      [
        'id'            =>  24,
        'type'          =>  0,
        'name'          =>  'Other - Networking & Information Systems',
        'desc'          =>  'Other - Networking & Information Systems',
        'order'         =>  3,
        'parent_id'     =>  20,
      ],
      [
        'id'            =>  25,
        'type'          =>  0,
        'name'          =>  'ERP / CRM Implementation',
        'desc'          =>  'ERP / CRM Implementation',
        'order'         =>  4,
        'parent_id'     =>  20,
      ],
      [
        'id'            =>  26,
        'type'          =>  0,
        'name'          =>  'Writing & Translation',
        'desc'          =>  'Writing & Translation',
        'order'         =>  3,
        'parent_id'     =>  null,
      ],
      [
        'id'            =>  27,
        'type'          =>  0,
        'name'          =>  'Technical Writing',
        'desc'          =>  'Technical Writing',
        'order'         =>  0,
        'parent_id'     =>  26,
      ],
      [
        'id'            =>  28,
        'type'          =>  0,
        'name'          =>  'Website Content',
        'desc'          =>  'Website Content',
        'order'         =>  1,
        'parent_id'     =>  26,
      ],
      [
        'id'            =>  29,
        'type'          =>  0,
        'name'          =>  'Blog & Article Writing',
        'desc'          =>  'Blog & Article Writing',
        'order'         =>  2,
        'parent_id'     =>  26,
      ],
      [
        'id'            =>  30,
        'type'          =>  0,
        'name'          =>  'Copywriting',
        'desc'          =>  'Copywriting',
        'order'         =>  3,
        'parent_id'     =>  26,
      ],
      [
        'id'            =>  31,
        'type'          =>  0,
        'name'          =>  'Other - Writing & Translation',
        'desc'          =>  'Other - Writing & Translation',
        'order'         =>  4,
        'parent_id'     =>  26,
      ],
      [
        'id'            =>  32,
        'type'          =>  0,
        'name'          =>  'Translation',
        'desc'          =>  'Translation',
        'order'         =>  5,
        'parent_id'     =>  26,
      ],
      [
        'id'            =>  33,
        'type'          =>  0,
        'name'          =>  'Creative Writing',
        'desc'          =>  'Creative Writing',
        'order'         =>  6,
        'parent_id'     =>  26,
      ],
      [
        'id'            =>  34,
        'type'          =>  0,
        'name'          =>  'Administrative Support',
        'desc'          =>  'Administrative Support',
        'order'         =>  4,
        'parent_id'     =>  null,
      ],
      [
        'id'            =>  35,
        'type'          =>  0,
        'name'          =>  'Data Entry',
        'desc'          =>  'Data Entry',
        'order'         =>  0,
        'parent_id'     =>  34,
      ],
      [
        'id'            =>  36,
        'type'          =>  0,
        'name'          =>  'Personal Assistant',
        'desc'          =>  'Personal Assistant',
        'order'         =>  1,
        'parent_id'     =>  34,
      ],
      [
        'id'            =>  37,
        'type'          =>  0,
        'name'          =>  'Web Research',
        'desc'          =>  'Web Research',
        'order'         =>  2,
        'parent_id'     =>  34,
      ],
      [
        'id'            =>  38,
        'type'          =>  0,
        'name'          =>  'Email Response Handling',
        'desc'          =>  'Email Response Handling',
        'order'         =>  3,
        'parent_id'     =>  34,
      ],
      [
        'id'            =>  39,
        'type'          =>  0,
        'name'          =>  'Other - Administrative Support',
        'desc'          =>  'Other - Administrative Support',
        'order'         =>  4,
        'parent_id'     =>  34,
      ],
      [
        'id'            =>  40,
        'type'          =>  0,
        'name'          =>  'Transcription',
        'desc'          =>  'Transcription',
        'order'         =>  5,
        'parent_id'     =>  34,
      ],
      [
        'id'            =>  41,
        'type'          =>  0,
        'name'          =>  'Design & Multimedia',
        'desc'          =>  'Design & Multimedia',
        'order'         =>  5,
        'parent_id'     =>  null,
      ],
      [
        'id'            =>  42,
        'type'          =>  0,
        'name'          =>  'Graphic Design',
        'desc'          =>  'Graphic Design',
        'order'         =>  0,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  43,
        'type'          =>  0,
        'name'          =>  'Logo Design',
        'desc'          =>  'Logo Design',
        'order'         =>  1,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  44,
        'type'          =>  0,
        'name'          =>  'Illustration',
        'desc'          =>  'Illustration',
        'order'         =>  2,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  45,
        'type'          =>  0,
        'name'          =>  'Print Design',
        'desc'          =>  'Print Design',
        'order'         =>  3,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  46,
        'type'          =>  0,
        'name'          =>  '3D Modeling & CAD',
        'desc'          =>  '3D Modeling & CAD',
        'order'         =>  4,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  47,
        'type'          =>  0,
        'name'          =>  'Audio Production',
        'desc'          =>  'Audio Production',
        'order'         =>  5,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  48,
        'type'          =>  0,
        'name'          =>  'Video Production',
        'desc'          =>  'Video Production',
        'order'         =>  6,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  49,
        'type'          =>  0,
        'name'          =>  'Voice Talent',
        'desc'          =>  'Voice Talent',
        'order'         =>  7,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  50,
        'type'          =>  0,
        'name'          =>  'Animation',
        'desc'          =>  'Animation',
        'order'         =>  8,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  51,
        'type'          =>  0,
        'name'          =>  'Other - Design & Multimedia',
        'desc'          =>  'Other - Design & Multimedia',
        'order'         =>  9,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  52,
        'type'          =>  0,
        'name'          =>  'Presentations',
        'desc'          =>  'Presentations',
        'order'         =>  10,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  53,
        'type'          =>  0,
        'name'          =>  'Engineering & Technical Design',
        'desc'          =>  'Engineering & Technical Design',
        'order'         =>  11,
        'parent_id'     =>  41,
      ],
      [
        'id'            =>  54,
        'type'          =>  0,
        'name'          =>  'Customer Service',
        'desc'          =>  'Customer Service',
        'order'         =>  6,
        'parent_id'     =>  null,
      ],
      [
        'id'            =>  55,
        'type'          =>  0,
        'name'          =>  'Customer Service & Support',
        'desc'          =>  'Customer Service & Support',
        'order'         =>  0,
        'parent_id'     =>  54,
      ],
      [
        'id'            =>  56,
        'type'          =>  0,
        'name'          =>  'Technical Support',
        'desc'          =>  'Technical Support',
        'order'         =>  1,
        'parent_id'     =>  54,
      ],
      [
        'id'            =>  57,
        'type'          =>  0,
        'name'          =>  'Phone Support',
        'desc'          =>  'Phone Support',
        'order'         =>  2,
        'parent_id'     =>  54,
      ],
      [
        'id'            =>  58,
        'type'          =>  0,
        'name'          =>  'Other - Customer Service',
        'desc'          =>  'Other - Customer Service',
        'order'         =>  3,
        'parent_id'     =>  54,
      ],
      [
        'id'            =>  59,
        'type'          =>  0,
        'name'          =>  'Order Processing',
        'desc'          =>  'Order Processing',
        'order'         =>  4,
        'parent_id'     =>  54,
      ],
      [
        'id'            =>  60,
        'type'          =>  0,
        'name'          =>  'Sales & Marketing',
        'desc'          =>  'Sales & Marketing',
        'order'         =>  7,
        'parent_id'     =>  null,
      ],
      [
        'id'            =>  61,
        'type'          =>  0,
        'name'          =>  'Advertising',
        'desc'          =>  'Advertising',
        'order'         =>  0,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  62,
        'type'          =>  0,
        'name'          =>  'Email Marketing',
        'desc'          =>  'Email Marketing',
        'order'         =>  1,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  63,
        'type'          =>  0,
        'name'          =>  'SEM - Search Engine Marketing',
        'desc'          =>  'SEM - Search Engine Marketing',
        'order'         =>  2,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  64,
        'type'          =>  0,
        'name'          =>  'SMM - Social Media Marketing',
        'desc'          =>  'SMM - Social Media Marketing',
        'order'         =>  3,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  65,
        'type'          =>  0,
        'name'          =>  'PR - Public Relations',
        'desc'          =>  'PR - Public Relations',
        'order'         =>  4,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  66,
        'type'          =>  0,
        'name'          =>  'Telemarketing & Telesales',
        'desc'          =>  'Telemarketing & Telesales',
        'order'         =>  5,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  67,
        'type'          =>  0,
        'name'          =>  'Market Research & Surveys',
        'desc'          =>  'Market Research & Surveys',
        'order'         =>  6,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  68,
        'type'          =>  0,
        'name'          =>  'Sales & Lead Generation',
        'desc'          =>  'Sales & Lead Generation',
        'order'         =>  7,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  69,
        'type'          =>  0,
        'name'          =>  'Other - Sales & Marketing',
        'desc'          =>  'Other - Sales & Marketing',
        'order'         =>  8,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  70,
        'type'          =>  0,
        'name'          =>  'SEO - Search Engine Optimization',
        'desc'          =>  'SEO - Search Engine Optimization',
        'order'         =>  9,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  71,
        'type'          =>  0,
        'name'          =>  'Business Plans & Marketing Strategy',
        'desc'          =>  'Business Plans & Marketing Strategy',
        'order'         =>  10,
        'parent_id'     =>  60,
      ],
      [
        'id'            =>  72,
        'type'          =>  0,
        'name'          =>  'Business Services',
        'desc'          =>  'Business Services',
        'order'         =>  8,
        'parent_id'     =>  null,
      ],
      [
        'id'            =>  73,
        'type'          =>  0,
        'name'          =>  'Accounting',
        'desc'          =>  'Accounting',
        'order'         =>  0,
        'parent_id'     =>  72,
      ],
      [
        'id'            =>  74,
        'type'          =>  0,
        'name'          =>  'HR / Payroll',
        'desc'          =>  'HR / Payroll',
        'order'         =>  1,
        'parent_id'     =>  72,
      ],
      [
        'id'            =>  75,
        'type'          =>  0,
        'name'          =>  'Financial Services & Planning',
        'desc'          =>  'Financial Services & Planning',
        'order'         =>  2,
        'parent_id'     =>  72,
      ],
      [
        'id'            =>  76,
        'type'          =>  0,
        'name'          =>  'Payment Processing',
        'desc'          =>  'Payment Processing',
        'order'         =>  3,
        'parent_id'     =>  72,
      ],
      [
        'id'            =>  77,
        'type'          =>  0,
        'name'          =>  'Legal',
        'desc'          =>  'Legal',
        'order'         =>  4,
        'parent_id'     =>  72,
      ],
      [
        'id'            =>  78,
        'type'          =>  0,
        'name'          =>  'Project Management',
        'desc'          =>  'Project Management',
        'order'         =>  5,
        'parent_id'     =>  72,
      ],
      [
        'id'            =>  79,
        'type'          =>  0,
        'name'          =>  'Business Consulting',
        'desc'          =>  'Business Consulting',
        'order'         =>  6,
        'parent_id'     =>  72,
      ],
      [
        'id'            =>  80,
        'type'          =>  0,
        'name'          =>  'Recruiting',
        'desc'          =>  'Recruiting',
        'order'         =>  7,
        'parent_id'     =>  72,
      ],
      [
        'id'            =>  81,
        'type'          =>  0,
        'name'          =>  'Statistical Analysis',
        'desc'          =>  'Statistical Analysis',
        'order'         =>  8,
        'parent_id'     =>  72,
      ],
      [
        'id'            =>  82,
        'type'          =>  0,
        'name'          =>  'Other - Business Services',
        'desc'          =>  'Other - Business Services',
        'order'         =>  9,
        'parent_id'     =>  72,
      ],
      [
        'id'            =>  83,
        'type'          =>  0,
        'name'          =>  'Bookkeeping',
        'desc'          =>  'Bookkeeping',
        'order'         =>  10,
        'parent_id'     =>  72,
      ],
    ];
    DB::table('categories')->insert($categories);
  }
}