<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class LanguagesSeeder extends Seeder {

  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    // Add languages.
    $languages = [
      [
        'id' => 1,
        'name' => 'Afrikaans (South Africa)',
        'code' => 'AF',
        'country' => 'ZA',
      ],
      [
        'id' => 2,
        'name' => 'Albanian (Albania)',
        'code' => 'SQ',
        'country' => 'AL',
      ],
      [
        'id' => 3,
        'name' => 'Alsatian (France)',
        'code' => 'GS',
        'country' => 'FR',
      ],
      [
        'id' => 4,
        'name' => 'Amharic (Ethiopia)',
        'code' => 'AM',
        'country' => 'FR',
      ],
      [
        'id' => 5,
        'name' => 'Arabic (Algeria)',
        'code' => 'AR',
        'country' => 'DZ',
      ],
      [
        'id' => 6,
        'name' => 'Arabic (Bahrain)',
        'code' => 'AR',
        'country' => 'BH',
      ],
      [
        'id' => 7,
        'name' => 'Arabic (Egypt)',
        'code' => 'AR',
        'country' => 'EG',
      ],
      [
        'id' => 8,
        'name' => 'Arabic (Iraq)',
        'code' => 'AR',
        'country' => 'IQ',
      ],
      [
        'id' => 9,
        'name' => 'Arabic (Jordan)',
        'code' => 'AR',
        'country' => 'JO',
      ],
      [
        'id' => 10,
        'name' => 'Arabic (Kuwait)',
        'code' => 'AR',
        'country' => 'KW',
      ],
      [
        'id' => 11,
        'name' => 'Arabic (Lebanon)',
        'code' => 'AR',
        'country' => 'LB',
      ],
      [
        'id' => 12,
        'name' => 'Arabic (Libya)',
        'code' => 'AR',
        'country' => 'LY',
      ],
      [
        'id' => 13,
        'name' => 'Arabic (Morocco)',
        'code' => 'AR',
        'country' => 'MA',
      ],
      [
        'id' => 14,
        'name' => 'Arabic (Oman)',
        'code' => 'AR',
        'country' => 'OM',
      ],
      [
        'id' => 15,
        'name' => 'Arabic (Qatar)',
        'code' => 'AR',
        'country' => 'QA',
      ],
      [
        'id' => 16,
        'name' => 'Arabic (Saudi Arabia)',
        'code' => 'AR',
        'country' => 'SA',
      ],
      [
        'id' => 17,
        'name' => 'Arabic (Syria)',
        'code' => 'AR',
        'country' => 'SY',
      ],
      [
        'id' => 18,
        'name' => 'Arabic (Tunisia)',
        'code' => 'AR',
        'country' => 'TN',
      ],
      [
        'id' => 19,
        'name' => 'Arabic (U.A.E.)',
        'code' => 'AR',
        'country' => 'AE',
      ],
      [
        'id' => 20,
        'name' => 'Arabic (Yemem)',
        'code' => 'AR',
        'country' => 'YE',
      ],
      [
        'id' => 21,
        'name' => 'Armenian (Armenia)',
        'code' => 'HY',
        'country' => 'AM',
      ],
      [
        'id' => 22,
        'name' => 'Assamese (India)',
        'code' => 'AS',
        'country' => 'IN',
      ],
      [
        'id' => 23,
        'name' => 'Azeri (Cyrillic, Azerbaijan)',
        'code' => 'AZ',
        'country' => 'AZ',
      ],
      [
        'id' => 24,
        'name' => 'Azeri (Latin, Azerbaijan)',
        'code' => 'AZ',
        'country' => 'AZ',
      ],
      [
        'id' => 25,
        'name' => 'Bashkir (Russia)',
        'code' => 'BA',
        'country' => 'RU',
      ],
      [
        'id' => 26,
        'name' => 'Basque (Basque)',
        'code' => 'EU',
        'country' => 'ES',
      ],
      [
        'id' => 27,
        'name' => 'Belarusian (Belarus)',
        'code' => 'BE',
        'country' => 'BY',
      ],
      [
        'id' => 28,
        'name' => 'Bengali (Bangladesh)',
        'code' => 'BN',
        'country' => 'BD',
      ],
      [
        'id' => 29,
        'name' => 'Bengali (India)',
        'code' => 'BN',
        'country' => 'IN',
      ],
      [
        'id' => 30,
        'name' => 'Bosnian (Cyrillic, Bosnia and Herzegovina)',
        'code' => 'BS',
        'country' => 'BA',
      ],
      [
        'id' => 31,
        'name' => 'Bosnian (Latin, Bosnia and Herzegovina)',
        'code' => 'BS',
        'country' => 'BA',
      ],
      [
        'id' => 32,
        'name' => 'Breton (France)',
        'code' => 'BR',
        'country' => 'FR',
      ],
      [
        'id' => 33,
        'name' => 'Bulgarian (Bulgaria)',
        'code' => 'BG',
        'country' => 'BG',
      ],
      [
        'id' => 34,
        'name' => 'Catalan (Catalan)',
        'code' => 'CA',
        'country' => 'ES',
      ],
      [
        'id' => 35,
        'name' => 'Chinese (Simplified, PRC)',
        'code' => 'CH',
        'country' => 'CN',
      ],
      [
        'id' => 36,
        'name' => 'Chinese (Traditional, Hong Kong S.A.R)',
        'code' => 'ZH',
        'country' => 'HK',
      ],
      [
        'id' => 37,
        'name' => 'Chinese (Traditional, Singapore)',
        'code' => 'ZH',
        'country' => 'SG',
      ],
      [
        'id' => 38,
        'name' => 'Chinese (Traditional, Taiwan)',
        'code' => 'CH',
        'country' => 'TW',
      ],
      [
        'id' => 39,
        'name' => 'Chinese (Traditional, Macao S.A.R.)',
        'code' => 'ZH',
        'country' => 'MO',
      ],
      [
        'id' => 40,
        'name' => 'Corsican (France)',
        'code' => 'CO',
        'country' => 'FR',
      ],
      [
        'id' => 41,
        'name' => 'Croatian (Croatia)',
        'code' => 'HR',
        'country' => 'HR',
      ],
      [
        'id' => 42,
        'name' => 'Croatian (Latin, Bosnia and Herzegovina)',
        'code' => 'HR',
        'country' => 'BA',
      ],
      [
        'id' => 43,
        'name' => 'Czech (Czech Republic)',
        'code' => 'CS',
        'country' => 'CZ',
      ],
      [
        'id' => 44,
        'name' => 'Danish (Denmark)',
        'code' => 'DA',
        'country' => 'DK',
      ],
      [
        'id' => 45,
        'name' => 'Dari (Afghanistan)',
        'code' => 'PR',
        'country' => 'AF',
      ],
      [
        'id' => 46,
        'name' => 'Divehi (Maldives)',
        'code' => 'DI',
        'country' => 'MV',
      ],
      [
        'id' => 47,
        'name' => 'Dutch (Belgium)',
        'code' => 'NL',
        'country' => 'BE',
      ],
      [
        'id' => 48,
        'name' => 'Dutch (Netherlands)',
        'code' => 'NL',
        'country' => 'NL',
      ],
      [
        'id' => 49,
        'name' => 'English (Australia)',
        'code' => 'EN',
        'country' => 'AU',
      ],
      [
        'id' => 50,
        'name' => 'English (Belize)',
        'code' => 'EN',
        'country' => 'BZ',
      ],
      [
        'id' => 51,
        'name' => 'English (Canada)',
        'code' => 'EN',
        'country' => 'CA',
      ],
/*      [
        'id' => 52,
        'name' => 'English (Caribbean)',
        'code' => 'EN',
        'country' => '',
      ],
*/
      [
        'id' => 53,
        'name' => 'English (India)',
        'code' => 'EN',
        'country' => 'IN',
      ],
      [
        'id' => 54,
        'name' => 'English (Ireland)',
        'code' => 'EN',
        'country' => 'IE',
      ],
      [
        'id' => 55,
        'name' => 'English (Jamaica)',
        'code' => 'EN',
        'country' => 'JM',
      ],
      [
        'id' => 56,
        'name' => 'English (Malaysia)',
        'code' => 'EN',
        'country' => 'MY',
      ],
      [
        'id' => 57,
        'name' => 'English (New Zealand)',
        'code' => 'EN',
        'country' => 'NZ',
      ],
      [
        'id' => 58,
        'name' => 'English (Republic of the Philippines)',
        'code' => 'EN',
        'country' => 'PH',
      ],
      [
        'id' => 59,
        'name' => 'English (Singapore)',
        'code' => 'EN',
        'country' => 'SG',
      ],
      [
        'id' => 60,
        'name' => 'English (South Africa)',
        'code' => 'EN',
        'country' => 'ZA',
      ],
      [
        'id' => 61,
        'name' => 'English (Trinidad and Tobago)',
        'code' => 'EN',
        'country' => 'TT',
      ],
      [
        'id' => 62,
        'name' => 'English (United Kingdom)',
        'code' => 'EN',
        'country' => 'GB',
      ],
      [
        'id' => 63,
        'name' => 'English (United State)',
        'code' => 'EN',
        'country' => 'US',
      ],
      [
        'id' => 64,
        'name' => 'English (Zimbabwe)',
        'code' => 'EN',
        'country' => 'ZW',
      ],
      [
        'id' => 65,
        'name' => 'English (Estonia)',
        'code' => 'EN',
        'country' => 'EE',
      ],
      [
        'id' => 66,
        'name' => 'Faroese (Faroe Islands)',
        'code' => 'FO',
        'country' => 'FO',
      ],
      [
        'id' => 67,
        'name' => 'Filipino (Philippines)',
        'code' => 'FP',
        'country' => 'PH',
      ],
      [
        'id' => 68,
        'name' => 'Finnish (Finland)',
        'code' => 'FI',
        'country' => 'FI',
      ],
      [
        'id' => 69,
        'name' => 'French (Belgium)',
        'code' => 'FR',
        'country' => 'BE',
      ],
      [
        'id' => 70,
        'name' => 'French (Canada)',
        'code' => 'FR',
        'country' => 'CA',
      ],
      [
        'id' => 71,
        'name' => 'French (France)',
        'code' => 'FR',
        'country' => 'FR',
      ],
      [
        'id' => 72,
        'name' => 'French (Luxembourg)',
        'code' => 'FR',
        'country' => 'LU',
      ],
      [
        'id' => 73,
        'name' => 'French (Monaco)',
        'code' => 'FR',
        'country' => 'MC',
      ],
      [
        'id' => 74,
        'name' => 'French (Switzerland)',
        'code' => 'FR',
        'country' => 'CH',
      ],
      [
        'id' => 75,
        'name' => 'Frisian (Netherlands)',
        'code' => 'FY',
        'country' => 'NL',
      ],
      [
        'id' => 76,
        'name' => 'Galician (Galician)',
        'code' => 'GL',
        'country' => 'ES',
      ],
      [
        'id' => 77,
        'name' => 'Georgian (Georgia)',
        'code' => 'KA',
        'country' => 'GE',
      ],
      [
        'id' => 78,
        'name' => 'German (Austria)',
        'code' => 'DE',
        'country' => 'AT',
      ],
      [
        'id' => 79,
        'name' => 'German (Germany)',
        'code' => 'DE',
        'country' => 'DE',
      ],
      [
        'id' => 80,
        'name' => 'German (Liechtenstein)',
        'code' => 'DE',
        'country' => 'LI',
      ],
      [
        'id' => 81,
        'name' => 'German (Luxembourg)',
        'code' => 'DE',
        'country' => 'LU',
      ],
      [
        'id' => 82,
        'name' => 'German (Switzerland)',
        'code' => 'DE',
        'country' => 'CH',
      ],
      [
        'id' => 83,
        'name' => 'Greek (Greece)',
        'code' => 'EL',
        'country' => 'GR',
      ],
      [
        'id' => 84,
        'name' => 'Greenlandic (Greenland)',
        'code' => 'KA',
        'country' => 'GL',
      ],
      [
        'id' => 85,
        'name' => 'Gujarati (India)',
        'code' => 'GU',
        'country' => 'IN',
      ],
      [
        'id' => 86,
        'name' => 'Hausa (Latin, Nigeria)',
        'code' => 'HA',
        'country' => 'NG',
      ],
      [
        'id' => 87,
        'name' => 'Hebrew (Israel)',
        'code' => 'HE',
        'country' => 'IL',
      ],
      [
        'id' => 88,
        'name' => 'Hindi (India)',
        'code' => 'HI',
        'country' => 'IN',
      ],
      [
        'id' => 89,
        'name' => 'Hungarian (Hungary)',
        'code' => 'HU',
        'country' => 'HU',
      ],
      [
        'id' => 90,
        'name' => 'Icelandic (Iceland)',
        'code' => 'IS',
        'country' => 'IS',
      ],
      [
        'id' => 91,
        'name' => 'Igbo (Nigeria)',
        'code' => 'IB',
        'country' => 'NG',
      ],
      [
        'id' => 92,
        'name' => 'Indonesian (Indonesia)',
        'code' => 'IN',
        'country' => 'ID',
      ],
      [
        'id' => 93,
        'name' => 'Inuktitut (Latin, Canada)',
        'code' => 'IU',
        'country' => 'CA',
      ],
      [
        'id' => 94,
        'name' => 'Inuktitut (Syllabics, Canada)',
        'code' => 'IU',
        'country' => 'CA',
      ],
      [
        'id' => 95,
        'name' => 'Irish (Ireland)',
        'code' => 'IR',
        'country' => 'IE',
      ],
      [
        'id' => 96,
        'name' => 'isiXhosa (South Africa)',
        'code' => 'XH',
        'country' => 'ZA',
      ],
      [
        'id' => 97,
        'name' => 'isiZulu (South Africa)',
        'code' => 'ZU',
        'country' => 'ZA',
      ],
      [
        'id' => 98,
        'name' => 'Italian (Italy)',
        'code' => 'IT',
        'country' => 'IT',
      ],
      [
        'id' => 99,
        'name' => 'Italian (Switzerland)',
        'code' => 'IT',
        'country' => 'CH',
      ],
      [
        'id' => 100,
        'name' => 'Japanese (Japan)',
        'code' => 'JP',
        'country' => 'JP',
      ],
      [
        'id' => 102,
        'name' => 'Kannada (India)',
        'code' => 'KD',
        'country' => 'IN',
      ],
      [
        'id' => 103,
        'name' => 'Kazakh (Kazakhstan)',
        'code' => 'KK',
        'country' => 'KZ',
      ],
      [
        'id' => 104,
        'name' => 'Khmer (Cambodia)',
        'code' => 'KH',
        'country' => 'KH',
      ],
      [
        'id' => 105,
        'name' => 'Kiche (Guatemala)',
        'code' => 'QU',
        'country' => 'GT',
      ],
      [
        'id' => 106,
        'name' => 'Kinyarwanda (Rwanda)',
        'code' => 'KI',
        'country' => 'RW',
      ],
      [
        'id' => 107,
        'name' => 'Kiswahili (Kenya)',
        'code' => 'SW',
        'country' => 'KE',
      ],
      [
        'id' => 108,
        'name' => 'Konkani (India)',
        'code' => 'KN',
        'country' => 'IN',
      ],
      [
        'id' => 109,
        'name' => 'Korean (Korea)',
        'code' => 'KO',
        'country' => 'KO',
      ],
      [
        'id' => 110,
        'name' => 'Korean (Korea, D.P.R.)',
        'code' => 'KP',
        'country' => 'KP',
      ],
      [
        'id' => 111,
        'name' => 'Kyrgyz (Kyrgyzstan)',
        'code' => 'KY',
        'country' => 'KG',
      ],
      [
        'id' => 112,
        'name' => 'Lao (Lao P.D.R.)',
        'code' => 'LA',
        'country' => 'LA',
      ],
      [
        'id' => 113,
        'name' => 'Latvian (Latvia)',
        'code' => 'LV',
        'country' => 'LV',
      ],
      [
        'id' => 114,
        'name' => 'Lithuanian (Lithuania)',
        'code' => 'LT',
        'country' => 'LT',
      ],
      [
        'id' => 115,
        'name' => 'Lower Sorbian (Germany)',
        'code' => 'DS',
        'country' => 'DE',
      ],
      [
        'id' => 116,
        'name' => 'Luxembourgish (Luxembourg)',
        'code' => 'LB',
        'country' => 'LU',
      ],
      [
        'id' => 117,
        'name' => 'Macedonian (Former Yugoslav Republic of Macedonia)',
        'code' => 'MK',
        'country' => 'MK',
      ],
      [
        'id' => 118,
        'name' => 'Malay (Brunei Darussalam)',
        'code' => 'MS',
        'country' => 'BN',
      ],
      [
        'id' => 119,
        'name' => 'Malay (Malaysia)',
        'code' => 'MS',
        'country' => 'MY',
      ],
      [
        'id' => 120,
        'name' => 'Malayalam (India)',
        'code' => 'MY',
        'country' => 'IN',
      ],
      [
        'id' => 121,
        'name' => 'Maltese (Malta)',
        'code' => 'ML',
        'country' => 'MT',
      ],
      [
        'id' => 122,
        'name' => 'Maori (New Zealand)',
        'code' => 'MR',
        'country' => 'NZ',
      ],
      [
        'id' => 123,
        'name' => 'Mapudungun (Chile)',
        'code' => 'MP',
        'country' => 'CL',
      ],
      [
        'id' => 124,
        'name' => 'Marathi (India)',
        'code' => 'MA',
        'country' => 'IN',
      ],
      [
        'id' => 125,
        'name' => 'Mohawk (Mohawk)',
        'code' => 'MW',
        'country' => 'CA',
      ],
      [
        'id' => 126,
        'name' => 'Mongolian (Cyrillic, Mongolia)',
        'code' => 'MN',
        'country' => 'MN',
      ],
      [
        'id' => 127,
        'name' => 'Mongolian (Traditional Mongolian, PRC)',
        'code' => 'MN',
        'country' => 'MN',
      ],
      [
        'id' => 128,
        'name' => 'Nepali (Nepal)',
        'code' => 'NE',
        'country' => 'NP',
      ],
      [
        'id' => 129,
        'name' => 'Norwegian, Bokmal (Norway)',
        'code' => 'NO',
        'country' => 'NO',
      ],
      [
        'id' => 130,
        'name' => 'Norwegian, Nynorsk (Norway)',
        'code' => 'NO',
        'country' => 'NO',
      ],
      [
        'id' => 131,
        'name' => 'Occitan (France)',
        'code' => 'OC',
        'country' => 'FR',
      ],
      [
        'id' => 132,
        'name' => 'Oriya (India)',
        'code' => 'OR',
        'country' => 'IN',
      ],
      [
        'id' => 133,
        'name' => 'Pashto (Afghanistan)',
        'code' => 'PA',
        'country' => 'AF',
      ],
      [
        'id' => 134,
        'name' => 'Persian',
        'code' => 'FA',
        'country' => 'IR',
      ],
      [
        'id' => 135,
        'name' => 'Polish (Poland)',
        'code' => 'PL',
        'country' => 'PL',
      ],
      [
        'id' => 136,
        'name' => 'Portuguese (Brazil)',
        'code' => 'PT',
        'country' => 'BR',
      ],
      [
        'id' => 137,
        'name' => 'Portuguese (Portugal)',
        'code' => 'PT',
        'country' => 'PT',
      ],
      [
        'id' => 138,
        'name' => 'Punjabi (India)',
        'code' => 'PA',
        'country' => 'IN',
      ],
      [
        'id' => 139,
        'name' => 'Quechua (Bolivia)',
        'code' => 'QU',
        'country' => 'BO',
      ],
      [
        'id' => 140,
        'name' => 'Quechua (Ecuador)',
        'code' => 'QU',
        'country' => 'EC',
      ],
      [
        'id' => 141,
        'name' => 'Quechua (Peru)',
        'code' => 'QU',
        'country' => 'PE',
      ],
      [
        'id' => 142,
        'name' => 'Romanian (Romania)',
        'code' => 'RO',
        'country' => 'RO',
      ],
      [
        'id' => 143,
        'name' => 'Romansh (Switzerland)',
        'code' => 'RM',
        'country' => 'CH',
      ],
      [
        'id' => 144,
        'name' => 'Russian (Russia)',
        'code' => 'RU',
        'country' => 'RU',
      ],
      [
        'id' => 145,
        'name' => 'Sami, Inari (Finland)',
        'code' => 'SM',
        'country' => 'FI',
      ],
      [
        'id' => 146,
        'name' => 'Sami, Lule (Norway)',
        'code' => 'SM',
        'country' => 'NO',
      ],
      [
        'id' => 147,
        'name' => 'Sami, Lule (Sweden)',
        'code' => 'SM',
        'country' => 'SE',
      ],
      [
        'id' => 148,
        'name' => 'Sami, Northern (Finland)',
        'code' => 'SM',
        'country' => 'FI',
      ],
      [
        'id' => 149,
        'name' => 'Sami, Northern (Norway)',
        'code' => 'SM',
        'country' => 'NO',
      ],
      [
        'id' => 150,
        'name' => 'Sami, Northern (Sweden)',
        'code' => 'SM',
        'country' => 'SE',
      ],
      [
        'id' => 151,
        'name' => 'Sami, Skolt (Finland)',
        'code' => 'SM',
        'country' => 'FI',
      ],
      [
        'id' => 152,
        'name' => 'Sami, Southern (Norway)',
        'code' => 'SM',
        'country' => 'NO',
      ],
      [
        'id' => 153,
        'name' => 'Sami, Southern (Sweden)',
        'code' => 'SM',
        'country' => 'SE',
      ],
      [
        'id' => 154,
        'name' => 'Sanskrit (India)',
        'code' => 'SA',
        'country' => 'IN',
      ],
      [
        'id' => 155,
        'name' => 'Scottish Gaelic (United Kingdom)',
        'code' => 'GL',
        'country' => 'GB',
      ],
      [
        'id' => 156,
        'name' => 'Serbian (Cyrillic, Bosnia and Herzegovina)',
        'code' => 'SR',
        'country' => 'BA',
      ],
      [
        'id' => 157,
        'name' => 'Serbian (Cyrillic, Montenegro)',
        'code' => 'SR',
        'country' => 'ME',
      ],
/*
      [
        'id' => 158,
        'name' => 'Serbian (Cyrillic, Serbia and Montenegro (Former))',
        'code' => 'SR',
        'country' => 'RS',
      ],
*/
      [
        'id' => 159,
        'name' => 'Serbian (Cyrillic, Serbia)',
        'code' => 'SR',
        'country' => 'RS',
      ],
      [
        'id' => 160,
        'name' => 'Serbian (Latin, Bosnia and Herzegovina)',
        'code' => 'SR',
        'country' => 'BA',
      ],
      [
        'id' => 161,
        'name' => 'Serbian (Latin, Montenegro)',
        'code' => 'SR',
        'country' => 'ME',
      ],
/*
      [
        'id' => 162,
        'name' => 'Serbian (Latin, Serbia and Montenegro (Former))',
        'code' => 'SR',
        'country' => 'PE',
      ],
*/
      [
        'id' => 163,
        'name' => 'Serbian (Latin, Serbia)',
        'code' => 'SR',
        'country' => 'RS',
      ],
      [
        'id' => 164,
        'name' => 'Sesotho sa Leboa (South Africa)',
        'code' => 'NS',
        'country' => 'ZA',
      ],
      [
        'id' => 165,
        'name' => 'Setswana (South Africa)',
        'code' => 'TS',
        'country' => 'ZA',
      ],
      [
        'id' => 166,
        'name' => 'Sinhala (Sri Lanka)',
        'code' => 'SI',
        'country' => 'LK',
      ],
      [
        'id' => 167,
        'name' => 'Slovak (Slovakia)',
        'code' => 'SK',
        'country' => 'SK',
      ],
      [
        'id' => 168,
        'name' => 'Slovenian (Slovenia)',
        'code' => 'SL',
        'country' => 'SI',
      ],
      [
        'id' => 169,
        'name' => 'Spanish (Argentina)',
        'code' => 'ES',
        'country' => 'AR',
      ],
      [
        'id' => 170,
        'name' => 'Spanish (Bolivarian Republic of Venezuela)',
        'code' => 'ES',
        'country' => 'VE',
      ],
      [
        'id' => 171,
        'name' => 'Spanish (Bolivia)',
        'code' => 'ES',
        'country' => 'BO',
      ],
      [
        'id' => 172,
        'name' => 'Spanish (Chile)',
        'code' => 'ES',
        'country' => 'CL',
      ],
      [
        'id' => 173,
        'name' => 'Spanish (Colombia)',
        'code' => 'ES',
        'country' => 'CO',
      ],
      [
        'id' => 174,
        'name' => 'Spanish (Costa Rica)',
        'code' => 'ES',
        'country' => 'CR',
      ],
      [
        'id' => 175,
        'name' => 'Spanish (Dominican Republic)',
        'code' => 'ES',
        'country' => 'DO',
      ],
      [
        'id' => 176,
        'name' => 'Spanish (Ecuador)',
        'code' => 'ES',
        'country' => 'EC',
      ],
      [
        'id' => 177,
        'name' => 'Spanish (El Salvador)',
        'code' => 'ES',
        'country' => 'SV',
      ],
      [
        'id' => 178,
        'name' => 'Spanish (Guatemala)',
        'code' => 'ES',
        'country' => 'GT',
      ],
      [
        'id' => 179,
        'name' => 'Spanish (Honduras)',
        'code' => 'ES',
        'country' => 'HN',
      ],
      [
        'id' => 180,
        'name' => 'Spanish (Mexico)',
        'code' => 'ES',
        'country' => 'MX',
      ],
      [
        'id' => 181,
        'name' => 'Spanish (Nicaragua)',
        'code' => 'ES',
        'country' => 'NI',
      ],
      [
        'id' => 182,
        'name' => 'Spanish (Panama)',
        'code' => 'ES',
        'country' => 'PA',
      ],
      [
        'id' => 183,
        'name' => 'Spanish (Paraguay)',
        'code' => 'ES',
        'country' => 'PY',
      ],
      [
        'id' => 184,
        'name' => 'Spanish (Peru)',
        'code' => 'ES',
        'country' => 'PE',
      ],
      [
        'id' => 185,
        'name' => 'Spanish (Puerto Rico)',
        'code' => 'ES',
        'country' => 'PR',
      ],
      [
        'id' => 186,
        'name' => 'Spanish (Spain, International Sort)',
        'code' => 'ES',
        'country' => 'ES',
      ],
      [
        'id' => 187,
        'name' => 'Spanish (Spain, Traditional Sort)',
        'code' => 'ES',
        'country' => 'ES',
      ],
      [
        'id' => 188,
        'name' => 'Spanish (United States)',
        'code' => 'ES',
        'country' => 'US',
      ],
      [
        'id' => 189,
        'name' => 'Spanish (Uruguay)',
        'code' => 'ES',
        'country' => 'UY',
      ],
      [
        'id' => 190,
        'name' => 'Swedish (Finland)',
        'code' => 'SV',
        'country' => 'FI',
      ],
      [
        'id' => 191,
        'name' => 'Swedish (Sweden)',
        'code' => 'SV',
        'country' => 'SE',
      ],
      [
        'id' => 192,
        'name' => 'Syriac (Syria)',
        'code' => 'SY',
        'country' => 'SY',
      ],
      [
        'id' => 193,
        'name' => 'Tajik (Cyrillic, Tajikistan)',
        'code' => 'TA',
        'country' => 'TJ',
      ],
      [
        'id' => 194,
        'name' => 'Tamazight (Latin, Algeria)',
        'code' => 'TZ',
        'country' => 'DZ',
      ],
      [
        'id' => 195,
        'name' => 'Tamil (India)',
        'code' => 'TA',
        'country' => 'IN',
      ],
      [
        'id' => 196,
        'name' => 'Tatar (Russia)',
        'code' => 'TT',
        'country' => 'RU',
      ],
      [
        'id' => 197,
        'name' => 'Telugu (India)',
        'code' => 'TE',
        'country' => 'IN',
      ],
      [
        'id' => 198,
        'name' => 'Thai (Thailand)',
        'code' => 'TH',
        'country' => 'TH',
      ],
      [
        'id' => 199,
        'name' => 'Tibetan (PRC)',
        'code' => 'BO',
        'country' => 'CN',
      ],
      [
        'id' => 200,
        'name' => 'Turkish (Turkey)',
        'code' => 'TR',
        'country' => 'TR',
      ],
      [
        'id' => 201,
        'name' => 'Turkmen (Turkmenistan)',
        'code' => 'TU',
        'country' => 'TM',
      ],
      [
        'id' => 202,
        'name' => 'Ukrainian (Ukraine)',
        'code' => 'UK',
        'country' => 'UA',
      ],
      [
        'id' => 203,
        'name' => 'Upper Sorbian (Germany)',
        'code' => 'HS',
        'country' => 'DE',
      ],
      [
        'id' => 204,
        'name' => 'Urdu (Islamic Republic of Pakistan)',
        'code' => 'UR',
        'country' => 'PK',
      ],
      [
        'id' => 205,
        'name' => 'Uyghur (PRC)',
        'code' => 'UI',
        'country' => 'CN',
      ],
      [
        'id' => 206,
        'name' => 'Uzbek (Cyrillic, Uzbekistan)',
        'code' => 'UZ',
        'country' => 'UZ',
      ],
      [
        'id' => 207,
        'name' => 'Uzbek (Latin, Uzbekistan)',
        'code' => 'UZ',
        'country' => 'UZ',
      ],
      [
        'id' => 208,
        'name' => 'Vietnamese (Vietnam)',
        'code' => 'VI',
        'country' => 'VN',
      ],
      [
        'id' => 209,
        'name' => 'Welsh (United Kingdom)',
        'code' => 'CY',
        'country' => 'GB',
      ],
      [
        'id' => 210,
        'name' => 'Wolof (Senegal)',
        'code' => 'WO',
        'country' => 'SN',
      ],
      [
        'id' => 211,
        'name' => 'Yakut (Russia)',
        'code' => 'SA',
        'country' => 'RU',
      ],
      [
        'id' => 212,
        'name' => 'Yi (PRC)',
        'code' => 'II',
        'country' => 'CN',
      ],
      [
        'id' => 213,
        'name' => 'Yoruba (Nigeria)',
        'code' => 'YO',
        'country' => 'NG',
      ],
    ];
    DB::table('languages')->insert($languages);
  }
}