@extends('layouts/home/index')

@section('css')

@endsection

@section('content')
<div class="row">
  <div class="col-xs-12 col-sm-3 nav-menu">
    @include('layouts/home/section/privacy_left')
  </div>

  <div class="col-xs-12 col-sm-9 border-left">
    <h1 class="section-title text-center font-gotham-bold">Privacy Policy</h1>
    <div class="body-content text-justify">

      <div style="float: right"><a title="TRUSTe Privacy Certification" href="http://privacy.truste.com/privacy-seal/validation?rid=a2e3cc13-e602-49fd-b4ac-6700f9189241" target="_blank"><img style="border: none" src="http://privacy-policy.truste.com/privacy-seal/seal?rid=d76cf885-4721-4993-be25-d4c0519d319b" alt="TRUSTe Privacy Certification"></a></div>
          <p>&nbsp;</p>
          <p><span style="font-weight: 400">Effective Date: May 11, 2016</span></p>
          <p><span style="font-weight: 400">Upwork Global Inc. (“</span><strong>Upwork</strong><span style="font-weight: 400">”) provides this Privacy Policy to let you know our policies and procedures regarding the collection, use and disclosure of information through </span><a href="../../index.html"><span style="font-weight: 400">www.upwork.com</span></a><span style="font-weight: 400"> (the “</span><strong>Site</strong><span style="font-weight: 400">”), and any other websites, features, applications, widgets or online services that are owned or controlled by Upwork and that post a link to this Privacy Policy (together with the Site, the “</span><strong>Service</strong><span style="font-weight: 400">”), as well as any information Upwork collects offline in connection with the Service. It also describes the choices available to you regarding the use of, your access to, and how to update and correct your personal information</span><i><span style="font-weight: 400">.</span></i> <strong>Note that we combine the information we collect from you from the Site, through the Service generally, or offline.</strong></p>
          <p><span style="font-weight: 400">The TRUSTe program covers only information that is collected through this website,</span><a href="../../index.html"> <span style="font-weight: 400">www.upwork.com</span></a><span style="font-weight: 400">,</span><span style="font-weight: 400"> and mobile website and does not cover information that may be collected through software downloaded from the website, or information collected behind the login of <a href="../../login.html">https://www.upwork.com/login</a> and through the mobile application.</span></p>
          <p><span style="font-weight: 400">In order to view our relationship with TRUSTe please visit the validation page visible by clicking on the TRUSTe seal. If you have an unresolved privacy or data use concern that we have not addressed satisfactorily, please contact TRUSTe </span><a href="https://feedback-form.truste.com/watchdog/request"><i><span style="font-weight: 400">here</span></i></a><span style="font-weight: 400">.</span></p>
          <p><span style="font-weight: 400">By accessing or using the Service, you consent to the information collection, disclosure and use practices described in this Privacy Policy. Please note that certain features or services referenced in this Privacy Policy may not be offered on the Service at all times. Please also review our </span><b>Terms of Service, </b><span style="font-weight: 400">which governs your use of the Service, and which is accessible at </span><a href="../terms/index.html"><b>https://www.upwork.com/legal/terms/</b></a><span style="font-weight: 400">.</span></p>
          <h2><strong>TABLE OF CONTENTS</strong></h2>
          <ol class="table-of-contents">
          <li><strong><a href="#information-collection">Information Collection</a></strong>
          <ul class="circled-list">
          <li><strong><a href="#information-you-provide-to-us">Information You Provide to Us</a></strong>
          <ul class="bulleted-list">
          <li><strong><a href="#personal-information">Personal Information</a></strong></li>
          <li><strong><a href="#payment-information">Payment Information</a></strong></li>
          <li><strong><a href="#identity-verification">Identity Verification</a></strong></li>
          <li><strong><a href="#general-audience-service">General Audience Service</a></strong></li>
          <li><strong><a href="#non-identifying-information">Non-Identifying Information</a></strong></li>
          <li><strong><a href="#combination-of-personal-and-non-identifying-information">Combination of Personal and Non-Identifying Information</a></strong></li>
          <li><a href="#Collection-of-the-Third-Party-Personal-Information"><strong>Collection of the Third Party Personal Information</strong></a></li>
          </ul>
          </li>
          <li><strong><a href="#information-received-from-third-parties">Information Received from Third Parties</a></strong></li>
          <li><strong><a href="#information-collected-from-users-automatically">Information Collected from Users Automatically</a></strong>
          <ul class="bulleted-list">
          <li><strong><a href="#cookies">Cookies</a></strong></li>
          <li><strong><a href="#web-beacons">Web Beacons</a></strong></li>
          <li><strong><a href="#embedded-scripts">Embedded Scripts</a></strong></li>
          </ul>
          </li>
          <li><strong><a href="#how-we-respond-to-do-not-track-signals">How We Respond to Do Not Track Signals</a></strong></li>
          <li><a href="#work-diaries"><strong>Work Diaries&nbsp;and Work View</strong></a></li>
          <li><strong><a href="#user-profiles">User Profiles</a></strong></li>
          <li><strong><a href="#community-forums">Community Forums</a></strong></li>
          <li><strong><a href="#testimonials">Testimonials</a></strong></li>
          <li><strong><a href="#work-listings-through-the-service">Work Listings Through the Service</a></strong></li>
          <li><strong><a href="#feedback">Feedback</a></strong></li>
          <li><strong><a href="#email-to-friends-and-referral-program">Email to Friends and Referral Program</a></strong></li>
          <li><strong><a href="#social-networking-services">Social Networking Services</a></strong></li>
          </ul>
          </li>
          <li><strong><a href="#use-and-retention-of-information">Use and Retention of Information</a></strong></li>
          <li><strong><a href="#information-sharing-and-disclosure">Information Sharing and Disclosure</a></strong>
          <ul class="circled-list">
          <li><strong><a href="#information-about-freelancers-shared-with-clients-and-agencies-or-teams">Information about Freelancers Shared with Clients and Agencies or Teams</a></strong></li>
          <li><strong><a href="#information-about-clients-and-agencies-shared-with-freelancers">Information about Clients and Agencies Shared with Freelancers</a></strong></li>
          <li><strong><a href="#service-providers">Service Providers</a></strong></li>
          <li><strong><a href="#what-happens-if-you-agree">What Happens if You Agree to Receive Information from Third Parties or Request That We Share Your Information</a></strong></li>
          <li><strong><a href="#legal-and-investigative-purposes">Legal and Investigative Purposes</a></strong></li>
          <li><strong><a href="#internal-and-business-transfers">Internal and Business Transfers</a></strong></li>
          <li><strong><a href="#sweepstakes-contests-and-promotions">Sweepstakes, Contests and Promotions</a></strong></li>
          </ul>
          </li>
          <li><strong><a href="#third-party-analytics">Third Party Analytics Providers, Ad Servers and Similar Third Parties</a></strong></li>
          <li><strong><a href="#your-choices-and-opting-out">Your Choices and Opting Out</a></strong></li>
          <li><strong><a href="#changing-your-information-or-closing-your-account">Changing Your Information or Closing Your Account</a></strong></li>
          <li><strong><a href="#security">Security</a></strong></li>
          <li><strong><a href="#international-transfers-of-personal-information">International Transfers of Personal Information</a></strong></li>
          <li><strong><a href="#links-to-other-sites">Links to Other Sites</a></strong></li>
          <li><strong><a href="#public-profile">Public Profile</a></strong></li>
          <li><strong><a href="#phishing">Phishing</a></strong></li>
          <li><strong><a href="#california-residents">California Residents – Your California Privacy Rights</a></strong></li>
          <li><strong><a href="#changes-to-this-policy">Changes to this Policy</a></strong></li>
          <li><strong><a href="#contacting-us">Contacting Us</a></strong></li>
          </ol>
          <section id="information-collection" class="p">
          <h4 id="information-collection">1. INFORMATION COLLECTION</h4>
          <p><span style="font-weight: 400">Users of the Service may be </span><strong>Clients</strong><span style="font-weight: 400"> (anyone utilizing the Upwork platform to request services to be performed by a Freelancer) or </span><strong>Freelancers</strong><span style="font-weight: 400"> (any company, individual user, or groups of associated individual users or companies utilizing the Upwork platform to offer services to Clients). Freelancers may also operate as an </span><strong>Agency</strong> <span style="font-weight: 400">(a legally recognized entity with the ability to hire and/or contract) with other Freelancers.</span></p>
          <p><strong><i id="information-you-provide-to-us">Information You Provide to Us</i></strong></p>
          <ul>
          <li id="personal-information" style="font-weight: 400"><strong>Personal Information:</strong><span style="font-weight: 400"> In the course of using the Service (whether as a Client or Freelancer), we may require or otherwise collect information that identifies you as a specific individual and can be used to contact or identify you (“<strong>Personal Information</strong>”). Examples of Personal Information include your name, email address, postal address and phone number.</span></li>
          <li id="payment-information" style="font-weight: 400"><strong>Payment Information:</strong><span style="font-weight: 400"> If you use the Service to make or receive payments, we will also collect certain payment information, such as credit card, PayPal or other financial account information, and billing address.</span></li>
          <li id="identity-verification" style="font-weight: 400"><strong>Identity Verification:</strong><span style="font-weight: 400"> We may collect Personal Information, such as your date of birth or taxpayer identification number, to validate your identity or as may be required by law, such as to complete tax filings. We may request documents to verify this information, such as a copy of your government-issued identification or photo or a billing statement.</span></li>
          <li id="general-audience-service" style="font-weight: 400"><strong>General Audience Service:</strong><span style="font-weight: 400"> The Service is general audience and intended for users 18 and older. We do not knowingly collect Personal Information from anyone younger than age 18. If we become aware that a child younger than 18 has provided us with Personal Information, we will use commercially reasonable efforts to delete such information from our files. If you are the parent or legal guardian of a child younger than age 18 and believe that Upwork has collected Personal Information from your child, please contact us at: </span><a href="mailto:legal@upwork.com"><span style="font-weight: 400">legal@upwork.com</span></a><span style="font-weight: 400">.</span></li>
          <li id="non-identifying-information" style="font-weight: 400"><strong>Non-Identifying Information/Usernames:</strong><span style="font-weight: 400"> We also may collect other information, such as zip codes, demographic data, information regarding your use of the Service, and general project-related data (“<strong>Non-Identifying Information</strong>”). We may aggregate information collected from Upwork registered and non-registered users (“</span><strong>Upwork Users</strong><span style="font-weight: 400">”). We consider usernames to be Non-Identifying Information. Usernames are made public through the Service and are viewable by other Upwork Users. </span></li>
          </ul>
          <p><span style="font-weight: 400">In some cases, we may render Personal Information (generally, email address) into a form of Non-Identifying Information referred to in this Privacy Policy as “<strong>Hashed Information</strong>.” This is typically accomplished using a mathematical process (commonly known as a hash function) to convert information into a code. The code does not identify you directly, but it may be used to connect your activity and interests.</span></p>
          <ul>
          <li id="combination-of-personal-and-non-identifying-information" style="font-weight: 400"><strong>Combination of Personal and Non-Identifying Information:</strong><span style="font-weight: 400"> Certain Non-Identifying Information would be considered a part of your Personal Information if it were combined with other identifiers in a way that enables you to be identified (for example, combining information with your name). But the same pieces of information are considered Non-Identifying Information when they are taken alone or combined only with other non-identifying information (for example, your viewing preferences). We may combine your Personal Information with Non-Identifying Information, but Upwork will treat the combined information as Personal Information.</span></li>
          <li id="Collection-of-the-Third-Party-Personal-Information" style="font-weight: 400"><strong>Collection of the Third Party Personal Information: </strong><span style="font-weight: 400">We collect the following personal information from you about your contacts or friends: First, last name and email address when you provide it to us for the purpose of adding your contacts to a message room.&nbsp;</span></li>
          </ul>
          <p><strong><i id="information-received-from-third-parties">Information Received from Third Parties</i></strong></p>
          <p><span style="font-weight: 400">We also may receive information about you from third parties. For example, we may supplement the information we collect with outside records or third parties may provide information in connection with a co-marketing agreement or at your request (such as if you choose to sign in with a third-party service). If we combine the information we receive from others with information we collect through the Service, we will treat the combined information as described in this Privacy Policy.</span></p>
          <p><strong><i id="information-collected-from-users-automatically">Information Collected from Users Automatically</i></strong></p>
          <p><span style="font-weight: 400">We and our third party service providers, including analytics and third party content providers, may automatically collect certain information from you whenever you access or interact with the Service. This information may include, among other information, the browser and operating system you are using, the URL or advertisement that referred you to the Service, the search terms you entered into a search engine that led you to the Service, areas within the Service that you visited, and other information commonly shared when browsers communicate with websites. We may combine this automatically collected log information with other information we collect about you. We do this to improve services we offer you, to improve marketing, analytics, and site functionality.</span></p>
          <p><span style="font-weight: 400">The information we collect also includes the Internet Protocol (“<strong>IP</strong>”) address or other unique device identifier (“<strong>Device Identifier</strong>”) for any device (computer, mobile phone, tablet, etc.) used to access the Service. A Device Identifier is a number that is automatically assigned or connected to the device you use to access the Service, and our servers identify your device by its Device Identifier. Some mobile service providers may also provide us or our third party service providers with information regarding the physical location of the device used to access the Service.</span></p>
          <p><strong><i>The technology used to collect information automatically from Upwork Users may include the following:</i></strong></p>
          <ul>
          <li style="font-weight: 400"><strong id="cookies">Cookies:</strong> <span style="font-weight: 400">Like many websites, we and our marketing partners, affiliates, analytics, and service providers use “cookies” to collect information. A cookie is a small data file that we transfer to your computer’s hard disk for record-keeping purposes. We use both persistent cookies that remain on your computer or similar device (such as to save your registration ID and login password for future logins to the Service and to track your compliance with the Upwork Terms of Service) and session ID cookies, which expire at the end of your browser session (for example, to enable certain features of the Service, to better understand how Upwork Users interact with the Service and to monitor aggregate usage by Upwork Users and web traffic routing on the Service). You may be able to instruct your browser, by changing its options, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. If you do not accept cookies, however, you may not be able to use all functionality of the Service.</span></li>
          </ul>
          <p><span style="font-weight: 400">We use Local Storage, such as HTML5, to store content information and preferences. Third parties with whom we partner to provide certain features on our website or to display advertising based upon your web browsing activity also use HTML5 to collect and store information. Various browsers may offer their own management tools for removing HTML5.</span></p>
          <p><span style="font-weight: 400">For further information on cookies and how they are used for the Service, please visit our Cookie Policy at </span><a href="../cookie-policy/index.html"><span style="font-weight: 400">https://www.upwork.com/legal/cookie-policy/</span></a><span style="font-weight: 400">.</span></p>
          <ul>
          <li style="font-weight: 400"><strong id="web-beacons">Web Beacons: </strong><span style="font-weight: 400">We and our marketing partners, affiliates, analytics, and service providers may also employ software technology known as “web beacons” and/or “tracking tags” to help us keep track of what content on our Service is effective and to serve relevant advertising to you. Web beacons are small graphics with a unique identifier that may be invisible to you, and which are used to track the online activity of Internet users. Web beacons are embedded in the web pages you review or email messages you receive. Web beacons or similar technologies may be used for a number of purposes, including, without limitation, to count visitors to our Service, to monitor how Upwork Users navigate the Service, to count how many emails that were sent were actually opened, or to count how many particular articles or links were actually viewed.</span></li>
          <li style="font-weight: 400"><strong id="embedded-scripts">Embedded Scripts:</strong><span style="font-weight: 400">&nbsp;We and our marketing partners, affiliates, analytics, and service providers may also employ software technology known as an</span> <span style="font-weight: 400">Embedded Script. An Embedded Script is programming code that is designed to collect information about your interactions with the Service, such as the links you click on. The code is temporarily downloaded onto your computer or other device and is deactivated or deleted when you disconnect from the Service.</span></li>
          </ul>
          <p><span style="font-weight: 400">In addition, we and our marketing partners, affiliates, analytics, and service providers may use a variety of other technologies (such as tags) that collect similar information for security and fraud detection purposes and we may use third parties to perform these services on our behalf.</span></p>
          <p><strong id="how-we-respond-to-do-not-track-signals">HOW WE RESPOND TO DO NOT TRACK SIGNALS</strong></p>
          <p><span style="font-weight: 400">Please note that your browser setting may allow you to automatically transmit a “Do Not Track” signal to websites and online service you visit. There is no consensus among industry participants as to what “Do Not Track” means in this context. Like many websites and online services, Upwork does not alter its practices when it receives a “Do Not Track” signal from a visitor’s browser. To find out more about “Do Not Track,” please visit </span><a href="http://www.allaboutdnt.com/"><span style="font-weight: 400">http://www.allaboutdnt.com</span></a><span style="font-weight: 400">.</span></p>
          <p><strong><i id="work-diaries">Work Diaries and Work View</i></strong><span style="font-weight: 400"> As part of the Service, we collect information about a Freelancer’s work on a project for a Client. This feature is known as Work Diary. Work Diaries include information provided by the Freelancer, such as a memo, as well as automatically gathered information about work on a project, such as number of mouseclicks and keyboard strokes and regularly taken screenshots (which may include a webcam picture of you if you have not disabled this feature in your settings). In order to use Work Diaries, you must download and install the Team App software from </span><a href="../../index.html"><span style="font-weight: 400">www.upwork.com</span></a><span style="font-weight: 400">.</span></p>
          <p><span style="font-weight: 400">We will share information contained in Work Diaries with the relevant Client and with any manager or administrator of any applicable Freelancer Agency. We inform Freelancers each time we capture information for Work Diary. As set forth in our Terms of Service, End User License Agreement, and help pages on the Site, a Freelancer may choose to block or delete the screen shot and associated data for a recorded work interval, but then the Freelancer may not be paid for that work interval. Upwork may use general information from Work Diaries for statistical analysis, product development, marketing and research.</span></p>
          <p><strong><i id="user-profiles">User Profiles </i></strong><span style="font-weight: 400">You may have the opportunity to create a profile, which consists of information about you, and may include Personal Information, photographs, examples of your work, information on work previously performed via the Service and outside the Service, skills, tests taken, test scores, hourly pay rates, feedback/rating information and other information, including your username (“<strong>Profile</strong>”). The information in your Profile may be visible to all Upwork Users and the general public subject to the privacy choices you make within your Upwork Profile. You may edit certain information in your Profile via your account and may choose to limit who is able to view certain content you post to your Profile. Clients and Agencies of associated individual users or companies may also have the opportunity to create an organization Profile. If, in any case, you believe that an unauthorized profile has been created about you, you can request for it to be removed by contacting us at </span><a href="https://support.upwork.com/"><span style="font-weight: 400">https://support.upwork.com</span></a><span style="font-weight: 400">.</span></p>
          <p><strong><i id="community-forums">Community Forums</i></strong><span style="font-weight: 400"> The Service may provide you the opportunity to participate and post content publicly in forums, on blogs, through interactive features Upwork and through other communication functionality (“<strong>Community Forums</strong>”). You may choose, through such features or otherwise, to submit or post questions, comments, or other content (collectively, “<strong>User Forum Content</strong>”). Please note that certain information, such as your name and Profile may be publicly displayed on the Service along with your User Forum Content. Please note that your use of Community Forums is subject to the Upwork Forum Rules and our Terms of Service.</span></p>
          <p><strong>Note that anything you post to a Community Forum is public <i>— </i>others will have access to your User Forum Content and may use it or share it with third parties. If you choose to voluntarily disclose Personal Information in your User Forum Content or use Community Forums to link to your Profile, that information will be considered public information and the protections of this Privacy Policy will not apply.</strong></p>
          <p><i><span style="font-weight: 400">To request removal of your personal information from our blog or community forum, contact us at </span></i><a href="https://support.upwork.com/"><i><span style="font-weight: 400">https://support.upwork.com</span></i></a><span style="font-weight: 400">. In some cases, we may not be able to remove your Personal Information, in which case we will let you know if we are unable to do so and why.</span></p>
          <p><strong><i id="testimonials">Testimonials</i></strong><span style="font-weight: 400"> We display personal testimonials of satisfied customers on our Service, in addition to other endorsements. With your consent we may post your testimonial along with your name. If you wish to update or delete your testimonial, you can contact us at https://support.upwork.com.</span></p>
          <p><strong><i id="work-listings-through-the-service">Work Listings Through the Service</i></strong></p>
          <p><span style="font-weight: 400">If you choose to post a work listing via the Service as a Client, the contents of such listing will be viewable publicly, unless you designate the listing as only viewable through the Service or as private using the settings available on the applicable website. Work listings include information such as budget, location, history of work listing(s) by the Client, the names of other Freelancers performing work for the Client, Client feedback and rating information and timing of project performance.</span></p>
          <p><strong><i id="feedback">Feedback</i></strong></p>
          <p><span style="font-weight: 400">We collect feedback from Upwork Users about their experience with other Upwork Users of our Service. Please note that any feedback you provide via the Service or feedback provided about you is publicly viewable via the Service. On very rare occasions, we may remove feedback pursuant to the relevant provisions of our Terms of Service, including the </span><a href="../terms-of-use/index.html"><span style="font-weight: 400">Terms of Use</span></a><span style="font-weight: 400">.</span></p>
          <p><strong><i id="email-to-friends-and-referral-program">Email to Friends and Referral Program</i></strong></p>
          <p><span style="font-weight: 400">Upwork lets you send project postings to friends via email. Upwork also offers the ability to send friends emails about providing or purchasing services through the Service. If you choose to use either feature, your friend’s email address will be used to send the requested posting and your email address will be used to copy you on the message to your friend or to send the message on your behalf. Upwork stores this information for the sole purpose of sending this one-time email and tracking the success of our referral program.</span></p>
          <p><span style="font-weight: 400">Your friend may contact us at support.upwork.com to request that we remove this information from our database.</span></p>
          <p><strong><i id="social-networking-services">Social Networking Services</i></strong></p>
          <p><span style="font-weight: 400">You may register to join the Service directly via the Service or by logging into your account with a third party social networking service (“<strong>SNS</strong>”) via our Service (e.g., Facebook, LinkedIn and other third party services that let you sign in using your existing credentials with those services). If you choose to register via an SNS, or to later link your account with the Service to your account with an SNS, we will use the Personal Information you have provided to the SNS (such as your name, email address, gender and other information you make publicly available via the SNS) to create your account. Note that the information we collect from and through an SNS may depend on the privacy settings you have set with the SNS and the permissions you grant to us in connection with linking your account with the Service to your account with an SNS. Other than what we may share with the SNS as described below, the Personal Information an SNS has about you is obtained by the SNS independent of our Service, and Upwork is not responsible for it.</span></p>
          <p><span style="font-weight: 400">The Upwork Service also may permit additional interactions between it and a third party website, service, or other content provider, such as enabling you to “like” or share content to a third party SNS. If you choose to “like” or share content, or to otherwise share information from or via our Service with a third party site or service, that information may be publicly displayed, and the third party may have access to information about you and your use of our Service (and we may have access to information about you from that third party). These features may collect your IP address, which page you are visiting on our site, and may set a cookie to enable the feature to function properly. Your interactions with third parties through an SNS or similar features are governed by the respective privacy policies of those third parties.</span></p>
          <p><span style="font-weight: 400">You represent that you are entitled to use your SNS account for the purposes described herein without breach by you of any of the terms and conditions that govern the SNS, and without obligating Upwork to pay any fees or making Upwork subject to any usage limitations imposed by such SNS. You can disable the link between your Upwork account and your SNS account at any time though the “Settings” section of our Service. Please note that your relationship with any SNS is governed solely by your agreement(s) with such SNS. If your SNS account terminates, then functions enabled through the link between your Upwork account and your SNS account will terminate as well.</span></p>
          </section>
          <h4 id="use-and-retention-of-information"><strong>2. USE AND RETENTION OF INFORMATION</strong></h4>
          <p><span style="font-weight: 400">WE USE INFORMATION WE COLLECT:</span></p>
          <ul>
          <li style="font-weight: 400"><span style="font-weight: 400">To provide and improve the Service, complete your transactions, and address your inquiries, process your registration, verify the information you provide is valid and for compliance and internal business purposes;</span></li>
          <li style="font-weight: 400"><span style="font-weight: 400">To contact you with administrative communications and Upwork newsletters, marketing or promotional materials (on behalf of Upwork or third parties) and other information that may be of interest to you. If you decide at any time that you no longer wish to receive such communications from us, please follow the instructions in the </span><a href="#your-choices-and-opting-out">Your Choices and Opting Out</a><span style="font-weight: 400"> section, below;</span></li>
          <li style="font-weight: 400"><span style="font-weight: 400">To tailor content we display to you and offers we may present to you, both on the Service and elsewhere online; </span></li>
          <li style="font-weight: 400"><span style="font-weight: 400">To administer and develop our business relationship with you and, if applicable, the corporation or other legal entity you represent;</span></li>
          <li style="font-weight: 400"><span style="font-weight: 400">To assess your proposal to perform a freelance project for Upwork and prepare related governmental and internal statistics reports; </span></li>
          <li style="font-weight: 400"><span style="font-weight: 400">To enforce and comply with the law, including to conduct an investigation, to protect the property and rights of Upwork or a third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, illegal, fraudulent, unethical or legally actionable activity. We may also use Device Identifiers to identify Upwork Users; and</span></li>
          <li style="font-weight: 400"><span style="font-weight: 400">For the purposes disclosed at the time you provide your information, with your consent, and as further described in this Privacy Policy.</span></li>
          </ul>
          <h4><span style="font-weight: 400">Unless you request that we delete certain information (see </span><a href="#changing-your-information-or-closing-your-account"><span style="font-weight: 400">Changing Your Information or Closing Your Account</span></a><span style="font-weight: 400"> below), we retain the information we collect for at least 5 years and may retain the information for as long as needed for our business and legal purposes.<br>
          </span></h4>
          <h4 id="information-sharing-and-disclosure"><strong>3. INFORMATION SHARING AND DISCLOSURE</strong></h4>
          <p><span style="font-weight: 400">We may share aggregated Non-Identifying Information and we may otherwise disclose Non-Identifying Information (including, without limitation, Hashed Information) to third parties. We do not share your Personal Information with third parties for those third parties’ marketing purposes unless we first provide you with the opportunity to opt-in to or opt-out of such sharing. We may also share the information we have collected about you, including Personal Information, as disclosed at the time you provide your information, with your consent, as otherwise described in this Privacy Policy, or in the following circumstances:</span></p>
          <ul>
          <li id="information-about-freelancers-shared-with-clients-and-agencies-or-teams" style="font-weight: 400"><strong>Information about Freelancers Shared with Clients and Agencies:</strong><b>&nbsp;</b><span style="font-weight: 400">We share information regarding Freelancers working on a Client project, including information in Work Diaries and work history, with Clients. Note that if a Freelancer is suspended from the Upwork Service, we may share that information with Clients for whom that Freelancer has worked or applied for work. We may also share information with Agencies to whom Freelancers are associated for a particular work project. If you choose to apply for work as a Freelancer via the Service, we will share information relevant to your application with the applicable Client(s), including, but not limited to, the information contained in your Freelancer Profile.</span></li>
          </ul>
          <ul>
          <li id="information-about-clients-and-agencies-shared-with-freelancers"><strong>Information about Clients and Agencies Shared with Freelancers:</strong><b><b> </b><span style="font-weight: 400">If you have entered into a service contract with another user, we may provide him/her with your name, address, or&nbsp;tax ID or VAT&nbsp;number in order to complete the transaction or to facilitate the resolution of a claim or dispute. The user receiving your information is not allowed to use it for purposes unrelated to the transaction, such as to contact you for marketing purposes, unless you have expressly consented to it.</span></b></li>
          </ul>
          <ul>
          <li id="service-providers" style="font-weight: 400"><strong>Service Providers: </strong><span style="font-weight: 400"><span style="font-weight: 400">We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Service-related services (e.g., without limitation, maintenance services, database management, web analytics and online advertising, payment processing, fraud detection and improvement of Upwork’s features) or to assist us in analyzing how our Service is used. These third parties may have access to your Personal Information in order to perform these tasks on our behalf.</span></span></li>
          <li id="what-happens-if-you-agree" style="font-weight: 400"><strong>What Happens If You Agree to Receive Information From Third Parties or Request That We Share Your Information</strong><span style="font-weight: 400"><span style="font-weight: 400"><strong>: </strong>You may be presented with an opportunity to receive information and/or marketing offers from one or more third parties. If you agree at that time to have your Personal Information shared, your Personal Information will be disclosed to that third party (or parties) and will be subject to the privacy policy and practices of that third party. We are not responsible for the privacy policies and practices of third parties, and, if you later decide that you no longer want to receive communications from a third party, you will need to contact that third party directly. You also may request, sometimes through your use of an SNS or similar interactive feature or third party application, that we share information about you with a third party and we will typically do so under those circumstances.</span></span></li>
          <li id="legal-and-investigative-purposes" style="font-weight: 400"><strong>Legal and Investigative Purposes:</strong><b>&nbsp;</b><span style="font-weight: 400"><span style="font-weight: 400">Upwork will share information with government agencies as required by law, including without limitation, in connection with reporting earnings. We cooperate with government and law enforcement officials and private parties to enforce and comply with the law. We will disclose information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate to respond to claims and legal process (including but not limited to subpoenas), at the request of governmental authorities or other third parties conducting an investigation, to protect the property and rights of Upwork or a third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, illegal, fraudulent, unethical or legally actionable activity. We may also use Device Identifiers to identify Upwork Users, and may do so in cooperation with third parties at our discretion.<br>
          </span></span></li>
          <li id="internal-and-business-transfers" style="font-weight: 400"><strong>Internal and Business Transfers: </strong><span style="font-weight: 400"><span style="font-weight: 400"><span style="font-weight: 400">Upwork may share information, including Personal Information, with its parent company Upwork Inc., subsidiaries, and affiliates, primarily for business and operational purposes. We may sell, transfer or otherwise share some or all of our assets, including your Personal Information, in connection with a merger, acquisition, reorganization or sale of assets (including, in each case, as part of the due-diligence process with any potential acquiring entity) or in the event of bankruptcy. You will be notified via email and/or a prominent notice on our website of any change in ownership or uses of your personal information, as well as any choices you may have regarding your personal information.</span></span></span></li>
          <li id="sweepstakes-contests-and-promotions" style="font-weight: 400"><strong>Sweepstakes, Contests and Promotions</strong><span style="font-weight: 400"><strong>:</strong> We may offer sweepstakes, contests, and other promotions (any, a “<strong>Promotion</strong>”) that may require registration. By participating in a Promotion, you are agreeing to the official rules that govern that Promotion, which may contain specific requirements of you, including, except where prohibited by law, allowing the sponsor(s) of the Promotion to use your name, voice, likeness or other indicia of persona in advertising or marketing associated with the Promotion. If you choose to enter a Promotion, your Personal Information may be disclosed to third parties or the public in connection with the administration of such Promotion, including, without limitation, in connection with winner selection, prize fulfillment, and as required by law or permitted by the Promotion’s official rules, such as on a winner’s list.</span></li>
          </ul>
          <h4 id="third-party-analytics">4. THIRD PARTY ANALYTICS PROVIDERS, AD SERVERS AND SIMILAR THIRD PARTIES</h4>
          <p><span style="font-weight: 400">Upwork works with (or may in the future work with) network advertisers, ad agencies, analytics service providers and other vendors to provide us with information regarding traffic on the Service, including pages viewed and the actions taken when visiting the Service; to serve our advertisements on other web sites, within mobile apps and elsewhere online; and to provide us with information regarding the use of the Service and the effectiveness of our advertisements. Our service providers may collect certain information about your visits to and activity on the Service as well as other websites or services, they may set and access their own tracking technologies on your device (including </span><a href="#cookies"><span style="font-weight: 400">cookies</span></a><span style="font-weight: 400"> and </span><a href="#web-beacons"><span style="font-weight: 400">web beacons</span></a><span style="font-weight: 400">), and may use that information to show you targeted advertisements. Some of these parties may collect Personal Information when you visit the Service or other online websites and services. We may also share certain Non-Identifying Information with these parties, including Hashed Information, in connection with the services they provide to us. </span></p>
          <p><span style="font-weight: 400">While we may use a variety of service providers to perform advertising services, some of these companies are members of the Network Advertising Initiative (“<strong>NAI</strong>”) or the Digital Advertising Alliance (“<strong>DAA</strong>”) Self-Regulatory Program for Online Behavioral Advertising. You may want to visit </span><a href="http://www.networkadvertising.org/managing/opt_out.asp"><span style="font-weight: 400">http://www.networkadvertising.org/managing/opt_out.asp</span></a><span style="font-weight: 400">, which provides information regarding targeted advertising and the “opt-out” procedures of NAI members. You may also want to visit or </span><a href="http://www.aboutads.info/choices/"><span style="font-weight: 400">http://www.aboutads.info/choices/</span></a><span style="font-weight: 400">, which provides information regarding targeted advertising and offers an “opt-out” by participating companies in the DAA Self-Regulatory Program. You may also opt-out by clicking </span><a href="http://preferences-mgr.truste.com/"><span style="font-weight: 400">here</span></a><span style="font-weight: 400"> (or if located in the European Union click </span><a href="http://www.youronlinechoices.eu/"><span style="font-weight: 400">here</span></a><span style="font-weight: 400">). Please note that opting out through these mechanisms does not opt you out of being served advertising, and you will continue to receive generic ads while online. </span></p>
          <h4 id="your-choices-and-opting-out">5. YOUR CHOICES AND OPTING OUT</h4>
          <p><span style="font-weight: 400">Registered Upwork Users may update their choices regarding the types of communications you receive from us through your online account. You also may opt-out of receiving marketing emails from us by following the opt-out instructions provided in those emails. Please note that we reserve the right to send you certain communications relating to your account or use of the Service (for example, administrative and service announcements) via email and other means and these transactional account messages may be unaffected if you opt-out from receiving marketing communications. You may opt-out of receiving text messages by replying “STOP” to any text message received. Registered Upwork Users who access the Service by using an Upwork mobile application may, with permission, receive push notifications. Similarly, registered Upwork Users who access the Service by using certain desktop browsers may, with permission, receive push notifications. Notification preferences can be modified in the settings menu for the mobile application or the applicable browser.</span></p>
          <section id="changing-information" class="p">
          <h4 id="changing-your-information-or-closing-your-account">6. CHANGING YOUR INFORMATION OR CLOSING YOUR ACCOUNT</h4>
          <p><span style="font-weight: 400">You are responsible for maintaining the accuracy of the information you submit to us, such as your contact information, and you must update any changes through your online account. If you request to access all personal information you’ve submitted, we will respond to your request to access within 30 days. If you completely delete all such information, then your account may become deactivated. If your account is deactivated or you ask to close your account, you will no longer be able to use the Service. If you would like us to delete your account in our system, you can do so through the Upwork Service (once you logged in, visit settings/ user settings, and then click on the close my account link). We will use commercially reasonable efforts to honor your request; however, certain information will actively persist on the Service even if you close your account, including information in your Work Diaries and messages you posted to the Service. In addition, your Personal Information may remain in our archives and information you update or delete, or information within a closed account, may persist internally or for our administrative purposes. It is not always possible to completely remove or delete information from our databases. In addition, we typically will not remove information you posted publicly through or on the Service. Bear in mind that neither you nor Upwork can delete all copies of information that has been previously shared with others on the Service.</span></p>
          <h4 id="security">7. SECURITY</h4>
          <p><span style="font-weight: 400">Upwork takes commercially reasonable steps to help protect and secure the information it collects and stores about Upwork Users. All access to the Site is encrypted using industry-standard transport layer security technology (TLS). When you enter sensitive information (such as tax identification number), we encrypt the transmission of that information using secure socket layer technology (SSL). We also use HTTP strict transport security to add an additional layer of protection for our Upwork Users. But remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. Thus, while we strive to protect your personal data, Upwork cannot ensure and does not warrant the security of any information you transmit to us.</span></p>
          <h4 id="international-transfers-of-personal-information">8. INTERNATIONAL TRANSFER OF PERSONAL INFORMATION</h4>
          <p><span style="font-weight: 400">Upwork is a United States company. If you are located outside the United States and choose to provide information to us, Upwork transfers Personal Information to the United States for processing. The U.S. may not have the same data protection laws as the country in which you initially provided the information. When we transfer your information to the U.S., we will protect it as described in this Privacy Policy. By visiting the Service, or providing Upwork with any information, you fully understand and unambiguously consent to this transfer, processing and storage of your information in the United States.</span></p>
          <p><span style="font-weight: 400">Upwork protects </span><span style="font-weight: 400">personally identifiable information from residents of the European Union, other European Economic Area countries, and Switzerland </span><span style="font-weight: 400">in accordance with applicable law </span><span style="font-weight: 400">(including, as applicable, reliance upon your consent and EU-approved standard contract clauses) and our commitment</span><span style="font-weight: 400">&nbsp;to the principles set forth in the Safe Harbor Framework. Upwork complies with and is certified under the Safe Harbor privacy framework as set forth by the U.S. Department of Commerce, European Commission and Switzerland regarding the collection, storage, use, transfer and other processing of Personal Information transferred from the European Economic Area or Switzerland to the U.S. To view our Safe Harbor Certification, click </span><a href="http://safeharbor.export.gov/companyinfo.aspx?id=24129"><span style="font-weight: 400">here</span></a><span style="font-weight: 400">.</span></p>
          <h4 id="links-to-other-sites">9. LINKS TO OTHER SITES</h4>
          <p><span style="font-weight: 400">Our Service contains links to other websites. If you choose to click on a third party link, you will be directed to that third party’s website. The fact that we link to a website is not an endorsement, authorization or representation of our affiliation with that third party, nor is it an endorsement of their privacy or information security policies or practices. We do not exercise control over third party websites. These other websites may place their own cookies or other files on your computer, collect data or solicit Personal Information from you. We encourage you to read the privacy policies or statements of the other websites you visit.</span></p>
          <h4 id="public-profile">10. PUBLIC PROFILE</h4>
          <p><span style="font-weight: 400">The profile you create on our site will be publicly accessible unless otherwise indicated. You may change the privacy settings of your profile through your account portal.</span></p>
          <h4 id="phishing">11. PHISHING</h4>
          <p><span style="font-weight: 400">Phishing websites imitate legitimate websites in order to obtain personal or financial information. Identity theft and the practice currently known as “phishing” are of great concern to Upwork. For more information about phishing, visit the website of the Federal Trade Commission at </span><a href="http://www.consumer.ftc.gov/articles/0003-phishing"><span style="font-weight: 400">http://www.consumer.ftc.gov/articles/0003-phishing</span></a><span style="font-weight: 400">. In addition, if you believe you have received an email or had a similar interaction with a third party pretending to be Upwork, please report it at </span><a href="https://support.upwork.com/"><span style="font-weight: 400">https://support.upwork.com</span></a><span style="font-weight: 400">.</span></p>
          <h4 id="california-residents">12. CALIFORNIA RESIDENTS – YOUR CALIFORNIA PRIVACY RIGHTS</h4>
          <p><span style="font-weight: 400">Pursuant to California Civil Code Section 1798.83, California residents who provide us with personal information in obtaining products or services for personal, family, or household use are entitled to request and obtain from us, one time per calendar year, information about the customer information we shared, if any, with other businesses for their own direct marketing uses. Alternatively, the law provides that a company may comply, as Upwork does, by disclosing in its privacy policy that it provides consumers choice (opt-in or opt-out) regarding sharing Personal Information with third parties for those third parties’ direct marketing purposes, and information on how to exercise that choice. As stated above in this Privacy Policy, Upwork provides you choice prior to sharing your personal information with third parties for their direct marketing purposes. If you do not opt-in or if you choose to opt-out at the time Upwork offers that choice, Upwork does not share your information with that identified third party for its direct marketing purposes.</span></p>
          <p><span style="font-weight: 400">If you are a California resident and you have questions about our practices with respect to sharing information with third parties for their direct marketing purposes and your ability to exercise choice, please send your request to the following email address: </span><a href="mailto:legal@upwork.com"><span style="font-weight: 400">legal@upwork.com</span></a><span style="font-weight: 400"> or write to us at the following mailing address:</span></p>
          <p><span style="font-weight: 400">Upwork </span><span style="font-weight: 400"><br>
          </span><span style="font-weight: 400">Attn: Legal </span><span style="font-weight: 400"><br>
          </span><span style="font-weight: 400">441 Logue Ave. </span><span style="font-weight: 400"><br>
          </span><span style="font-weight: 400">Mountain View, CA 94043</span></p>
          <p><span style="font-weight: 400">You must put the statement “Your California Privacy Rights” in the subject field of your email or include it in your writing if you choose to write to us at the designated mailing address. You must include your name, street address, city, state, and ZIP code. We will respond to you at your mailing address or, at our option, your email address. We are not responsible for notices that are not labeled or sent properly, or do not have complete information.</span></p>
          <h4 id="changes-to-this-policy">13. CHANGES TO THIS POLICY</h4>
          <p><span style="font-weight: 400">Upwork may update this Privacy Policy at any time and any changes will be effective upon posting. In the event that there are material changes to the way we treat your Personal Information, we will display a notice through the Services prior to the change becoming effective. We may also notify you by email, in our discretion. However, we will use your Personal Information in a manner consistent with the Privacy Policy in effect at the time you submitted the information, unless you consent to the new or revised policy.</span></p>
          <h4 id="contacting-us">14. CONTACTING US</h4>
          <p><span style="font-weight: 400">If you have any questions about this Privacy Policy, please contact us at </span><a href="https://support.upwork.com/"><span style="font-weight: 400">https://support.upwork.com</span></a><span style="font-weight: 400">; or by mail addressed to Upwork, Attn: Legal, 441 Logue Ave., Mountain View, CA 94043.</span></p>
          </section>

        </div>
  </div>

</div>
@endsection